name: servant-realworld-example-app
version: '0.1.0.0'
category: Web
author: Konstantin Zudov
maintainer: co@zudov.me
copyright: Konstantin Zudov 2016
license: BSD3
github: zudov/servant-realworld-example-app
extra-source-files:
- README.md
default-extensions:
- TypeApplications
- DataKinds
- TypeOperators
- NoImplicitPrelude
library:
  source-dirs: src
  exposed-modules:
  - RealWorld.Api
  dependencies:
  - base >= 4.7 && <5
  - wai
  - servant-server
  - text
executables:
  servant-realworld-example-app-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && <5
    - servant-realworld-example-app
    - wai
    - wai-extra
    - warp
    - servant-server
    - rapid
