name: realworld-app
version: '0.1.0.0'
category: Web
author: Konstantin Zudov
maintainer: co@zudov.me
copyright: Konstantin Zudov 2016
license: BSD3
github: zudov/servant-realworld-example-app
extra-source-files:
- README.md
default-extensions:
- DataKinds
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GADTs
- KindSignatures
- NoImplicitPrelude
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators
- MultiParamTypeClasses
- FunctionalDependencies
- ViewPatterns
- RankNTypes

library:
  source-dirs: src
  ghc-options:
    - -Wall
  exposed-modules:
  - RealWorld.Api
  - RealWorld.Monad
  - RealWorld.Prelude
  - RealWorld.DB  
  dependencies:
  - base >= 4.7 && <5
  - bytestring
  - wai
  - servant-server
  - text
  - mtl
  - aeson
  - containers
  - unordered-containers
  - hashable
  - http-types
  - vector
  - time
  - http-api-data
  - slug
  - exceptions
  - monad-time
  - acid-state
  - safecopy
  - cereal
executables:
  realworld-app-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && <5
    - realworld-app
    - wai
    - wai-extra
    - warp
    - servant-server
    - rapid
    - mtl
    - acid-state
